### ISSUE TITLE
Causes problem if serveral recipients used

### ISSUE THREAD

**Issue by wini2** [krausandre/wsm-form-spamshield#12]
Spamshield work fine if only one recipient is used (I don' have a CC or BCC in use). After adding a second recipient only the first gets an email.

TYPO3 10, wsm-form-spamshield 1.3.2

**Comment by krausandre** [comment]
Hi @wini2,
thank you for pinging me up. I tried to reproduce it, but I can't.
Since the Spamshield does not handle anything due to the mail finisher nor the recipients, this is surprising me.
Are you sure that this behavior is related to the Spamshield? How do you reproduce it? Can you give me some more insights to your setup?

Best regards
André

**Comment by wini2** [comment]
Wow, what an instant reply! Thanks for answering that fast. After a few more tests, I have to ask for apology for annoying you with that unjustified post, because it seems the problem lies with TYPO3 oder the form-extension.

Best regards
wini2
