### ISSUE TITLE
does not work in my form!?

### ISSUE THREAD

**Issue by kurtkk** [krausandre/wsm-form-spamshield#2]
This ist the result after sending the form content:

{"mousemove":152,"seconds":90,"displayWidth":2560,"displayHeight":1080,"formRend ....

No real message but a lot of LOG-entries!?

**Comment by krausandre** [comment]
Well this is a bit less information. The 'content' is part of the checks, which are done in the frontend. Where do you see them? 
Which TYPO3 version? Which PHP Version? Composer installation or legacy installation?
Please provide a useful explanation, otherwise I'm not able to help you.

Are you aware of that this is not a Captcha or something like that? Full verification works invisible to the user as IMHO there is no need to bother the visitor with annoying questions and stuff like that?

**Comment by kurtkk** [comment]
After having sent the form-content. The "Confirmation.html" - Finisher shows the result for the user an the above mentioned Content was shown in the field for the extension item in the form.
TYPO3 V11.5.25; PHP V8, also tried V7.4; no composer installation.

I know, that your Ext. / function is better than all Captchas!  ;-)

**Comment by krausandre** [comment]
@kurtkk I got your point and did some different tries to get it work. I'm not really happy with my current solution, but it does the trick for now. I will try to get some more input on that, maybe I can replace the current workaround with a better suitable solution  one day. For now, there is a version 1.2.0, which fixes that issue.

Maybe you might come back and tell me, if it works for you now. :)
Thx in advanced
